name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: composer install
      - uses: ankane/setup-postgres@v1
        with:
          database: pgvector_php_test
          dev-files: true
      - run: |
          cd /tmp
          git clone --branch v0.4.1 https://github.com/pgvector/pgvector.git
          cd pgvector
          make
          sudo make install
      - run: composer test
      - run: php examples/pgsql.php
